-- ─── Seed SGI ─────────────────────────────────────────────────────────────────
INSERT INTO sgis (name, country, country_code, phone, min_deposit, opening_fees) VALUES
('ATTIJARI SECURITIES WEST AFRICA (ASWA)', 'Côte d\'Ivoire', 'CI', '+225 27 20 21 98 26', NULL, NULL),
('ATLANTIQUE FINANCE', 'Côte d\'Ivoire', 'CI', '+225 27 20 21 59 75', NULL, NULL),
('BICI BOURSE', 'Côte d\'Ivoire', 'CI', '+225 27 20 20 16 68', NULL, NULL),
('BNI FINANCES', 'Côte d\'Ivoire', 'CI', '+225 27 20 20 99 02', NULL, NULL),
('BOA CAPITAL SECURITIES', 'Côte d\'Ivoire', 'CI', '+225 27 20 30 34 29', NULL, NULL),
('BRIDGE SECURITIES', 'Côte d\'Ivoire', 'CI', '+225 27 20 30 77 17', NULL, NULL),
('BSIC CAPITAL', 'Côte d\'Ivoire', 'CI', '+225 27 20 31 71 11', NULL, NULL),
('EDC INVESTMENT CORPORATION', 'Côte d\'Ivoire', 'CI', '+225 27 20 21 50 00', NULL, NULL),
('GEK CAPITAL', 'Côte d\'Ivoire', 'CI', '+225 27 24 35 00 44', NULL, NULL),
('HUDSON & CIE', 'Côte d\'Ivoire', 'CI', '+225 27 20 31 55 00', NULL, NULL),
('KERALES FINANCE', 'Côte d\'Ivoire', 'CI', '+225 07 98 90 27 27', NULL, NULL),
('MAC - AFRICAN SGI', 'Côte d\'Ivoire', 'CI', '+225 27 20 22 72 13', NULL, NULL),
('MATHA SECURITIES', 'Côte d\'Ivoire', 'CI', '+225 27 20 24 30 30', NULL, NULL),
('NSIA FINANCE', 'Côte d\'Ivoire', 'CI', '+225 27 20 29 06 53', NULL, NULL),
('ORAGROUP SECURITIES', 'Côte d\'Ivoire', 'CI', '+225 27 20 25 55 55', NULL, NULL),
('PHOENIX CAPITAL MANAGEMENT', 'Côte d\'Ivoire', 'CI', '+225 27 20 25 75 90', NULL, NULL),
('SIRIUS CAPITAL', 'Côte d\'Ivoire', 'CI', '+225 27 20 24 24 65', NULL, NULL),
('SOCIÉTÉ GÉNÉRALE CAPITAL SECURITIES WEST AFRICA', 'Côte d\'Ivoire', 'CI', '+225 27 20 20 12 65', '250 000 FCFA', NULL),
('ABCO BOURSE', 'Sénégal', 'SN', '+221 33 822 68 00', NULL, NULL),
('CGF BOURSE', 'Sénégal', 'SN', '+221 33 864 97 97', NULL, NULL),
('EVERSET FINANCE', 'Sénégal', 'SN', '+221 33 822 87 00', NULL, NULL),
('FGI', 'Sénégal', 'SN', '+221 33 867 60 42', NULL, NULL),
('IMPAXIS SECURITIES', 'Sénégal', 'SN', '+221 33 869 31 40', NULL, NULL),
('INVICTUS CAPITAL FINANCE', 'Sénégal', 'SN', '+221 33 864 58 58', NULL, NULL),
('AFRICABOURSE', 'Bénin', 'BJ', '+229 21 31 88 36', '100 000 FCFA', '11 000 FCFA'),
('AFRICAINE DE GESTION ET D\'INTERMÉDIATION (AGI)', 'Bénin', 'BJ', '+229 21 31 97 33', NULL, NULL),
('BIIC FINANCIAL SERVICES (BFS)', 'Bénin', 'BJ', '+229 21 32 48 75', NULL, NULL),
('SGI BÉNIN', 'Bénin', 'BJ', '+229 21 32 48 75', NULL, NULL),
('UNITED CAPITAL FOR AFRICA', 'Bénin', 'BJ', '+229 61 18 18 00', NULL, NULL),
('CORIS BOURSE', 'Burkina Faso', 'BF', '+226 50 33 04 91', '50 000 FCFA', 'Gratuit'),
('FINANCE INTERNATIONALE (IFI)', 'Burkina Faso', 'BF', '+226 70 88 89 89', NULL, NULL),
('SOCIÉTÉ AFRICAINE D\'INGÉNIERIE ET D\'INTERMÉDIATION FINANCIÈRE (SA2IF)', 'Burkina Faso', 'BF', '+226 25 36 15 13', '60 000 FCFA', '14 000 FCFA'),
('SOCIÉTÉ BURKINABÈ D\'INTERMÉDIATION FINANCIÈRE (SBIF)', 'Burkina Faso', 'BF', '+226 50 31 23 23', NULL, NULL),
('CIA-BOURSE SA', 'Mali', 'ML', '+223 20 23 50 20', NULL, NULL),
('GLOBAL CAPITAL', 'Mali', 'ML', '+223 44 90 59 74', NULL, NULL),
('SGI MALI', 'Mali', 'ML', '+223 20 29 29 72', NULL, NULL),
('SGI NIGER', 'Niger', 'NE', '+227 20 73 78 18', NULL, NULL),
('SGI TOGO', 'Togo', 'TG', '+228 22 22 30 86', '150 000 FCFA', '10 000 FCFA');

-- ─── Seed SGO ─────────────────────────────────────────────────────────────────
INSERT INTO sgos (name, country, country_code, address, phone, email, website, partner_sgi) VALUES
('AFRICA ASSET MANAGEMENT', 'Burkina Faso', 'BF', '01 BP 5394 Ouagadougou 01', '+226 50 33 04 90', NULL, NULL, NULL),
('AFRICABOURSE ASSET MANAGEMENT', 'Bénin', 'BJ', 'Av. Mgr Steinmetz 01 BP 6002 Cotonou', NULL, NULL, 'africabourse.com', 'Africabourse SGI'),
('AFRICAM SA', 'Côte d\'Ivoire', 'CI', 'Abidjan', NULL, NULL, NULL, 'SBIF SGI'),
('ATLANTIC ASSET MANAGEMENT (AAM)', 'Côte d\'Ivoire', 'CI', 'Abidjan', NULL, NULL, NULL, 'Atlantique Finance SGI'),
('ATTIJARI ASSET MANAGEMENT', 'Sénégal', 'SN', 'Place de l\'Indépendance BP 129 Dakar', NULL, NULL, 'attijarigestion.com', 'Attijari Securities West Africa'),
('BAOBAB ASSET MANAGEMENT (BAM)', 'Sénégal', 'SN', 'Dakar', NULL, NULL, NULL, 'FGI SGI'),
('BNI GESTION', 'Côte d\'Ivoire', 'CI', '01 BP 670 Abidjan 01', '+225 20 31 07 78', 'info@bnigestion.net', 'bnigestion.net', 'BNI Finance SGI'),
('BOA ASSET MANAGEMENT', 'Côte d\'Ivoire', 'CI', '01 BP 4132 Abidjan 01', '+225 20 30 34 01', 'information@boaam.com', 'bank-of-africa.net', 'BOA Capital Securities SGI'),
('BRIDGE ASSET MANAGEMENT', 'Côte d\'Ivoire', 'CI', '33 Av. Gén. De Gaulle, 01 BP 13108 Abidjan', '+225 20 25 97 97', NULL, NULL, 'Bridge Securities SGI'),
('BRM ASSET MANAGEMENT', 'Sénégal', 'SN', 'Imm. La Rotonde, Rue A.A Ndoye, Dakar', '+221 33 823 63 83', 'msakho@brmbank.com', 'brmbank.com', NULL),
('CGF GESTION', 'Sénégal', 'SN', '12 Rue Dr Thèze, BP 11516 Dakar', NULL, 'cgfbrvm@orange.sn', 'cgfgestion.com', 'CGF Bourse SGI'),
('CORIS ASSET MANAGEMENT', 'Burkina Faso', 'BF', '01 BP 6585 Ouagadougou 01', '+226 50 33 14 83', NULL, NULL, 'Coris Bourse SGI'),
('ECOBANK ASSET MANAGEMENT (EDC/EAM)', 'Côte d\'Ivoire', 'CI', '01 BP 4107 Abidjan 01', '+225 20 21 10 41', 'eam@ecobank.com', 'ecobank.com', 'EDC Investment Corporation SGI'),
('ENKO CAPITAL WEST AFRICA', 'Côte d\'Ivoire', 'CI', 'Abidjan', NULL, NULL, 'enkocapital.com', 'EDC Investment Corporation SGI'),
('IMPAXIS ASSET MANAGEMENT', 'Sénégal', 'SN', 'Dakar', NULL, NULL, NULL, 'Impaxis Securities SGI'),
('NSIA ASSET MANAGEMENT', 'Côte d\'Ivoire', 'CI', 'Abidjan', '+225 20 33 90 93', NULL, NULL, 'NSIA Finance SGI'),
('OPTI ASSET MANAGEMENT', 'Togo', 'TG', 'Imm. UTB Grand Marché, 3è Ét., Lomé', '+228 22 10 53 00', 'gassigbi@yahoo.fr', NULL, 'OAM SGI Togo'),
('PHOENIXAFRICA ASSET MANAGEMENT', 'Côte d\'Ivoire', 'CI', '10è Ét. Tour BIAO, Abidjan Plateau', '+225 20 37 28 04', NULL, 'phoenixafricaholding.com', 'Phoenix Capital Management SGI'),
('SAPHIR ASSET MANAGEMENT', 'Bénin', 'BJ', 'Cotonou', NULL, NULL, NULL, 'SGI Bénin / AGI'),
('SGA2E', 'Côte d\'Ivoire', 'CI', 'Bd de Marseille, Imm. DEMO, Abidjan', '+225 21 23 30 06', NULL, NULL, NULL),
('SGO MALI FINANCE (SMF)', 'Mali', 'ML', 'BP E 2477 Bamako', '+223 20 29 29 75', NULL, NULL, 'SGI Mali'),
('SOAGA', 'Bénin', 'BJ', 'Av. Jean Paul II, 08 BP 960 Cotonou', '+229 21 31 88 15', 'info@soaga.org', 'soaga.org', 'BOA Capital Securities / AGI'),
('SOGESPAR', 'Côte d\'Ivoire', 'CI', '01 BP 1355 Abidjan 01', '+225 20 20 14 89', 'niamien.kouadio@socgen.com', NULL, 'Sogebourse SGI (filiale SG)'),
('UCAMWAL (United Capital AM)', 'Côte d\'Ivoire', 'CI', 'Abidjan', NULL, NULL, NULL, 'UBA CI SGI'),
('WAFI CAPITAL S.A.', 'Bénin', 'BJ', 'Cotonou', NULL, NULL, NULL, 'AGI Bénin SGI');

-- ─── Seed Fonds OPCVM ─────────────────────────────────────────────────────────
-- On récupère les IDs des SGO dynamiquement avec des sous-requêtes

INSERT INTO sgo_funds (sgo_id, name, category, vl_current, perf_week)
SELECT id, 'FCP AAM EPARGNE CROISSANCE', 'D', 12369.60, '+0.70%' FROM sgos WHERE name = 'AFRICABOURSE ASSET MANAGEMENT' UNION ALL
SELECT id, 'FCP AAM OBLIGATIS', 'OATC', 9384.72, '+0.04%' FROM sgos WHERE name = 'AFRICABOURSE ASSET MANAGEMENT' UNION ALL
SELECT id, 'FCP AAM EPARGNE ACTION', 'A', 11395.08, '+1.02%' FROM sgos WHERE name = 'AFRICABOURSE ASSET MANAGEMENT' UNION ALL
SELECT id, 'FCP AAM SERENITIS', 'OATC', 12780.64, '+0.12%' FROM sgos WHERE name = 'AFRICABOURSE ASSET MANAGEMENT' UNION ALL

SELECT id, 'FCP EXPANSIO', 'D', NULL, NULL FROM sgos WHERE name = 'AFRICAM SA' UNION ALL
SELECT id, 'FCP SECURITAS', 'OMLT', NULL, NULL FROM sgos WHERE name = 'AFRICAM SA' UNION ALL
SELECT id, 'FCP VALORIS', 'A', NULL, NULL FROM sgos WHERE name = 'AFRICAM SA' UNION ALL
SELECT id, 'FCP CAPITAL PLUS', 'D', 1599.25, '+0.10%' FROM sgos WHERE name = 'AFRICAM SA' UNION ALL
SELECT id, 'FCP CONFORT PLUS', 'OMLT', 1510.97, '-0.03%' FROM sgos WHERE name = 'AFRICAM SA' UNION ALL

SELECT id, 'FCP ATLANTIQUE CROISSANCE', 'D', NULL, NULL FROM sgos WHERE name = 'ATLANTIC ASSET MANAGEMENT (AAM)' UNION ALL
SELECT id, 'FCP ATLANTIQUE LIQUIDITE', 'OCT', NULL, NULL FROM sgos WHERE name = 'ATLANTIC ASSET MANAGEMENT (AAM)' UNION ALL
SELECT id, 'FCP ATLANTIQUE ACTIONS', 'A', NULL, NULL FROM sgos WHERE name = 'ATLANTIC ASSET MANAGEMENT (AAM)' UNION ALL
SELECT id, 'FCP ATLANTIQUE SERENITE', 'OMLT', NULL, NULL FROM sgos WHERE name = 'ATLANTIC ASSET MANAGEMENT (AAM)' UNION ALL
SELECT id, 'FCP ATLANTIQUE HORIZON', 'D', NULL, NULL FROM sgos WHERE name = 'ATLANTIC ASSET MANAGEMENT (AAM)' UNION ALL
SELECT id, 'FCP ATLANTIQUE SECURITE', 'OMLT', NULL, NULL FROM sgos WHERE name = 'ATLANTIC ASSET MANAGEMENT (AAM)' UNION ALL

SELECT id, 'ATTIJARI OBLIG', 'OMLT', 14606.36, '+0.03%' FROM sgos WHERE name = 'ATTIJARI ASSET MANAGEMENT' UNION ALL
SELECT id, 'ATTIJARI LIQUIDITE', 'OCT', 16057.19, '+0.08%' FROM sgos WHERE name = 'ATTIJARI ASSET MANAGEMENT' UNION ALL
SELECT id, 'ATTIJARI HORIZON', 'OMLT', 16941.82, '+0.08%' FROM sgos WHERE name = 'ATTIJARI ASSET MANAGEMENT' UNION ALL
SELECT id, 'ATTIJARI ACTIONS', 'A', 26657.68, '-0.60%' FROM sgos WHERE name = 'ATTIJARI ASSET MANAGEMENT' UNION ALL
SELECT id, 'ATTIJARI DIVERSIFIE', 'D', 25039.72, '-0.17%' FROM sgos WHERE name = 'ATTIJARI ASSET MANAGEMENT' UNION ALL
SELECT id, 'ATTIJARI INVEST', 'OMLT', 16062.61, '+0.07%' FROM sgos WHERE name = 'ATTIJARI ASSET MANAGEMENT' UNION ALL
SELECT id, 'ATTIJARI PATRIMOINE', 'OMLT', 15939.57, '+0.08%' FROM sgos WHERE name = 'ATTIJARI ASSET MANAGEMENT' UNION ALL
SELECT id, 'CRBC-PROSPERITE', 'OMLT', 12437.04, '-0.04%' FROM sgos WHERE name = 'ATTIJARI ASSET MANAGEMENT' UNION ALL
SELECT id, 'WAFA ASSURANCE UEMOA', 'OMLT', 11499.70, '+0.09%' FROM sgos WHERE name = 'ATTIJARI ASSET MANAGEMENT' UNION ALL
SELECT id, 'FCP CRAT PERFORMANCE', 'D', 13802.36, '-0.22%' FROM sgos WHERE name = 'ATTIJARI ASSET MANAGEMENT' UNION ALL

SELECT id, 'FCP BAM TRESOR', 'OCT', 11684.63, '+0.04%' FROM sgos WHERE name = 'BAOBAB ASSET MANAGEMENT (BAM)' UNION ALL
SELECT id, 'FCP BAM WURUS', 'A', 16954.39, '+4.00%' FROM sgos WHERE name = 'BAOBAB ASSET MANAGEMENT (BAM)' UNION ALL

SELECT id, 'FCP CAPITAL CROISSANCE', 'D', NULL, NULL FROM sgos WHERE name = 'BNI GESTION' UNION ALL
SELECT id, 'OBLIG SECURITE', 'OMLT', NULL, NULL FROM sgos WHERE name = 'BNI GESTION' UNION ALL
SELECT id, 'FCP DYNAMIC SAVINGS', 'A', NULL, NULL FROM sgos WHERE name = 'BNI GESTION' UNION ALL
SELECT id, 'FCP INITIATIVES SOLIDARITE', 'D', 6318.00, '+1.31%' FROM sgos WHERE name = 'BNI GESTION' UNION ALL
SELECT id, 'FCPE SODEFOR', 'D', 8506.00, '-0.42%' FROM sgos WHERE name = 'BNI GESTION' UNION ALL
SELECT id, 'FCP PAM Actions', 'A', 25316.60, '+1.41%' FROM sgos WHERE name = 'BNI GESTION' UNION ALL
SELECT id, 'FCP PAM Diversifié Équilibré', 'D', 21407.27, '+0.62%' FROM sgos WHERE name = 'BNI GESTION' UNION ALL
SELECT id, 'FCP PAM Diversifié Obligations', 'D', 17939.25, '+0.90%' FROM sgos WHERE name = 'BNI GESTION' UNION ALL
SELECT id, 'FCPE CNRA', 'D', 4196.00, '-0.12%' FROM sgos WHERE name = 'BNI GESTION' UNION ALL
SELECT id, 'FCPE BNI RETRAITE', 'D', 5596.00, '+3.19%' FROM sgos WHERE name = 'BNI GESTION' UNION ALL
SELECT id, 'FCP KARIMA ETHIQUE', 'D', 2421.00, '+0.62%' FROM sgos WHERE name = 'BNI GESTION' UNION ALL

SELECT id, 'FCP Emergence', 'D', NULL, NULL FROM sgos WHERE name = 'BOA ASSET MANAGEMENT' UNION ALL
SELECT id, 'FCP Treso Monea', 'OCT', NULL, NULL FROM sgos WHERE name = 'BOA ASSET MANAGEMENT' UNION ALL
SELECT id, 'FCP ACTIONS PHARMACIE', 'D', 1286.64, '+0.28%' FROM sgos WHERE name = 'BOA ASSET MANAGEMENT' UNION ALL
SELECT id, 'FCP SALAM CI', 'D', 1247.56, '-0.02%' FROM sgos WHERE name = 'BOA ASSET MANAGEMENT' UNION ALL
SELECT id, 'FCP AL BARAKA 2', 'D', 1347.63, '+0.16%' FROM sgos WHERE name = 'BOA ASSET MANAGEMENT' UNION ALL
SELECT id, 'FCP ASSUR SENEGAL', 'D', 1692341.18, '+0.86%' FROM sgos WHERE name = 'BOA ASSET MANAGEMENT' UNION ALL
SELECT id, 'FCP PLACEMENT CROISSANCE', 'A', 2036.58, '+1.11%' FROM sgos WHERE name = 'BOA ASSET MANAGEMENT' UNION ALL
SELECT id, 'FCP POSTEFINANCES HORIZON', 'D', 2713.46, '+0.71%' FROM sgos WHERE name = 'BOA ASSET MANAGEMENT' UNION ALL
SELECT id, 'FCP PLACEMENT QUIETUDE', 'O', 1785.89, '+0.34%' FROM sgos WHERE name = 'BOA ASSET MANAGEMENT' UNION ALL
SELECT id, 'FCP LIQUIDITE-OPTIMUM', 'D', 14179.22, '+0.25%' FROM sgos WHERE name = 'BOA ASSET MANAGEMENT' UNION ALL
SELECT id, 'FCP BNDE VALEURS', 'D', 1506.82, '+0.55%' FROM sgos WHERE name = 'BOA ASSET MANAGEMENT' UNION ALL
SELECT id, 'FCP Global Investors', 'D', 52924.28, '+3.46%' FROM sgos WHERE name = 'BOA ASSET MANAGEMENT' UNION ALL
SELECT id, 'FCP Boa Obligations', 'OMLT', 13511.95, '+0.12%' FROM sgos WHERE name = 'BOA ASSET MANAGEMENT' UNION ALL
SELECT id, 'FCP Boa Sécurité', 'OMLT', 120368.08, '+0.32%' FROM sgos WHERE name = 'BOA ASSET MANAGEMENT' UNION ALL
SELECT id, 'FCP Boa Actions', 'A', 24015.44, '+3.25%' FROM sgos WHERE name = 'BOA ASSET MANAGEMENT' UNION ALL
SELECT id, 'FCP Boa Rendement', 'OMLT', 39684878.02, '+0.15%' FROM sgos WHERE name = 'BOA ASSET MANAGEMENT' UNION ALL

SELECT id, 'FCP BRIDGE EQUILIBRE', 'D', 43701153.33, '+1.28%' FROM sgos WHERE name = 'BRIDGE ASSET MANAGEMENT' UNION ALL
SELECT id, 'FCP BRIDGE DIVERSIFIE CROISSANCE', 'D', 9025.56, '+1.33%' FROM sgos WHERE name = 'BRIDGE ASSET MANAGEMENT' UNION ALL
SELECT id, 'FCP BRIDGE OBLIGATIONS', 'OMLT', 6861.84, '+0.07%' FROM sgos WHERE name = 'BRIDGE ASSET MANAGEMENT' UNION ALL

SELECT id, 'FCPCR SONATEL', 'D', 11315.75, '+2.26%' FROM sgos WHERE name = 'CGF GESTION' UNION ALL
SELECT id, 'FCPE FORCE PAD', 'D', 2508.02, '+1.36%' FROM sgos WHERE name = 'CGF GESTION' UNION ALL
SELECT id, 'FCPE SINI GNESIGUI', 'D', 2169.93, '+2.32%' FROM sgos WHERE name = 'CGF GESTION' UNION ALL
SELECT id, 'FCP EXPAT', 'D', 1366.30, '+2.34%' FROM sgos WHERE name = 'CGF GESTION' UNION ALL
SELECT id, 'FCP CAPITAL RETRAITE', 'D', 1319.57, '+1.20%' FROM sgos WHERE name = 'CGF GESTION' UNION ALL
SELECT id, 'FCP RENTE PERPETUELLE', 'D', 1308.97, '+1.70%' FROM sgos WHERE name = 'CGF GESTION' UNION ALL
SELECT id, 'FCP WALO', 'D', 1374.22, '+1.81%' FROM sgos WHERE name = 'CGF GESTION' UNION ALL
SELECT id, 'FCP DJOLOF', 'O', 1383.48, '+0.48%' FROM sgos WHERE name = 'CGF GESTION' UNION ALL
SELECT id, 'FCP IMPACT DIASPORA', 'D', 1217.16, '+0.11%' FROM sgos WHERE name = 'CGF GESTION' UNION ALL
SELECT id, 'FCP IFC-BOAD', 'O', 151560.14, '+0.20%' FROM sgos WHERE name = 'CGF GESTION' UNION ALL
SELECT id, 'FCPE DP WORLD DAKAR', 'D', 1673.57, '+1.56%' FROM sgos WHERE name = 'CGF GESTION' UNION ALL
SELECT id, 'FCPR SEN FONDS OPCR', 'OPCR', 11605.21, '-0.05%' FROM sgos WHERE name = 'CGF GESTION' UNION ALL
SELECT id, 'FCP TRANSVIE', 'D', 1226.67, '+0.91%' FROM sgos WHERE name = 'CGF GESTION' UNION ALL
SELECT id, 'SICAV Abdou DIOUF', 'D', 17589150.52, '+0.32%' FROM sgos WHERE name = 'CGF GESTION' UNION ALL
SELECT id, 'FCP BOAD CAPITAL RETRAITE', 'OMLT', 14657.84, '+0.01%' FROM sgos WHERE name = 'CGF GESTION' UNION ALL
SELECT id, 'FCP SOAGA EPARGNE OBLIGATIONS', 'OMLT', 6605.90, '+0.00%' FROM sgos WHERE name = 'CGF GESTION' UNION ALL
SELECT id, 'FCP SOAGA EPARGNE ACTIONS', 'A', 13190.72, '+0.85%' FROM sgos WHERE name = 'CGF GESTION' UNION ALL
SELECT id, 'FCP SOAGA EPARGNE SERENITE', 'OMLT', 17226.87, '+0.00%' FROM sgos WHERE name = 'CGF GESTION' UNION ALL
SELECT id, 'FCP SOAGA EPARGNE QUIETUDE', 'OMLT', 6401.28, '+0.01%' FROM sgos WHERE name = 'CGF GESTION' UNION ALL
SELECT id, 'FCP SOAGA EPARGNE DYNAMIQUE', 'A', 8448.41, '+0.85%' FROM sgos WHERE name = 'CGF GESTION' UNION ALL
SELECT id, 'FCP SOAGA TRESORERIE', 'M', 10482.74, '+0.01%' FROM sgos WHERE name = 'CGF GESTION' UNION ALL
SELECT id, 'FCP SOAGA EPARGNE ACTIVE', 'D', 15624.78, '+0.65%' FROM sgos WHERE name = 'CGF GESTION' UNION ALL

SELECT id, 'FCP CORIS ACTIONS', 'A', 11989.47, '+0.90%' FROM sgos WHERE name = 'CORIS ASSET MANAGEMENT' UNION ALL
SELECT id, 'FCP ASSURANCES', 'OCT', 5994.70, '+0.02%' FROM sgos WHERE name = 'CORIS ASSET MANAGEMENT' UNION ALL
SELECT id, 'FCP CORIS PERFORMANCE', 'D', 11166.18, '+0.77%' FROM sgos WHERE name = 'CORIS ASSET MANAGEMENT' UNION ALL

SELECT id, 'FCP ECOBANK UEMOA DIVERSIFIE', 'D', 10618.00, '+0.85%' FROM sgos WHERE name = 'ECOBANK ASSET MANAGEMENT (EDC/EAM)' UNION ALL
SELECT id, 'FCP ECOBANK UEMOA OBLIGATAIRE', 'OMLT', 20780.00, NULL FROM sgos WHERE name = 'ECOBANK ASSET MANAGEMENT (EDC/EAM)' UNION ALL
SELECT id, 'FCP ECOBANK UEMOA RENDEMENT', 'OMLT', 2056500.00, '+0.48%' FROM sgos WHERE name = 'ECOBANK ASSET MANAGEMENT (EDC/EAM)' UNION ALL
SELECT id, 'FCP ECOBANK ACTIONS UEMOA', 'A', 6294.00, '+1.40%' FROM sgos WHERE name = 'ECOBANK ASSET MANAGEMENT (EDC/EAM)' UNION ALL

SELECT id, 'FCP SAPHIR DYNAMIQUE', 'D', 7743.25, '+0.28%' FROM sgos WHERE name = 'ENKO CAPITAL WEST AFRICA' UNION ALL
SELECT id, 'FCP SAPHIR QUIETUDE', 'OMLT', 6697.53, '-0.01%' FROM sgos WHERE name = 'ENKO CAPITAL WEST AFRICA' UNION ALL

SELECT id, 'FCP SDE', 'D', 2706.00, '+0.12%' FROM sgos WHERE name = 'IMPAXIS ASSET MANAGEMENT' UNION ALL

SELECT id, 'EVOLUTIS', 'D', 6912.06, '+3.30%' FROM sgos WHERE name = 'NSIA ASSET MANAGEMENT' UNION ALL

SELECT id, 'FCP-1 OPTI PLACEMENT', 'A', NULL, NULL FROM sgos WHERE name = 'OPTI ASSET MANAGEMENT' UNION ALL
SELECT id, 'FCP-2 OPTI REVENU', 'OMLT', NULL, NULL FROM sgos WHERE name = 'OPTI ASSET MANAGEMENT' UNION ALL
SELECT id, 'FCP-3 OPTI CAPITAL', 'D', NULL, NULL FROM sgos WHERE name = 'OPTI ASSET MANAGEMENT' UNION ALL

SELECT id, 'FCP GLOBAL INVESTORS', 'D', 52924.28, '+3.46%' FROM sgos WHERE name = 'PHOENIXAFRICA ASSET MANAGEMENT' UNION ALL

SELECT id, 'FCP SAPHIR DYNAMIQUE', 'D', 7743.25, '+0.28%' FROM sgos WHERE name = 'SAPHIR ASSET MANAGEMENT' UNION ALL
SELECT id, 'FCP SAPHIR QUIETUDE', 'OMLT', 6697.53, '-0.01%' FROM sgos WHERE name = 'SAPHIR ASSET MANAGEMENT' UNION ALL

SELECT id, 'FCP NYESIGUI', 'D', NULL, NULL FROM sgos WHERE name = 'SGO MALI FINANCE (SMF)' UNION ALL
SELECT id, 'FCPE ORANGE MALI', 'D', 38904.09, '+1.13%' FROM sgos WHERE name = 'SGO MALI FINANCE (SMF)' UNION ALL
SELECT id, 'FCP TOUNKARANKE', 'OMLT', 132002.88, '+0.91%' FROM sgos WHERE name = 'SGO MALI FINANCE (SMF)' UNION ALL

SELECT id, 'United Capital Sapphire', 'D', 5487.00, '+0.46%' FROM sgos WHERE name = 'UCAMWAL (United Capital AM)' UNION ALL
SELECT id, 'United Capital Diamond', 'OMLT', 110066.42, '+0.00%' FROM sgos WHERE name = 'UCAMWAL (United Capital AM)' UNION ALL

SELECT id, 'SICAV WAFI CAPITAL', 'D', NULL, NULL FROM sgos WHERE name = 'WAFI CAPITAL S.A.';
